spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: VOTER-SERVICE
          uri: lb://VOTER-SERVICE
          predicates:
            - Path=/voter/**
            - Path=/votes/**
#        - id: FRONTEND-SERVER
#          uri: lb://FRONTEND-SERVER
#          predicates:
#            - Path=/ui/**
        - id: CONSTITUENCY-SERVICE
          uri: lb://CONSTITUENCY-SERVICE
          predicates:
            - Path=/constituency/**
            - Path=/polling/**
        - id: CANDIDATE-SERVICE
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/candidate/**
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/